BEGIN {
    print "/* This file is autogenerated from " ARGV[1] " . DO NOT edit */"
    print "extern void run_tests(void);"
    print "extern void do_start_test(const char *descr);"
    print "extern void do_end_test(void);"    
    print "void run_tests(void) {"
}

NF > 2 && $2 == "T" && $3 ~ /^testcase_/ {
    print "extern void " $3 "(void);"
    print "extern const char " $3 "_descr[];"
    print "do_start_test(" $3 "_descr);"
    print $3 "();"
    print "do_end_test();"
}

END {
    print "}"
}


